"""Tool manifests for CVE MCP server tools."""
from __future__ import annotations

try:
    from utils.tool_manifest_index import ToolAffordance, ToolManifest  # type: ignore[import-not-found]
except ImportError:
    from app.agentic.eol.utils.tool_manifest_index import ToolAffordance, ToolManifest  # type: ignore[import-not-found]


MANIFESTS: list[ToolManifest] = [
    ToolManifest(
        tool_name="search_cve",
        source="cve",
        domains=frozenset({"sre_cost_security"}),
        tags=frozenset({"cve", "security", "vulnerability", "search"}),
        affordance=ToolAffordance.READ,
        example_queries=(
            "search CVEs for Windows Server",
            "find critical vulnerabilities affecting nginx",
            "look up CVE-2024-1234",
        ),
        conflicts_with=frozenset({"search_cve_cache", "search_cve_live"}),
        conflict_note=(
            "search_cve is the default CVE search entrypoint. It uses cached data first and can fall back to live data. "
            "Use search_cve_cache only when the user explicitly wants cache-only results, and search_cve_live only when the user explicitly wants live-only results."
        ),
        preferred_over=frozenset({"search_cve_cache", "search_cve_live"}),
        primary_phrasings=(
            "search CVEs",
            "find vulnerabilities",
            "look up a CVE",
            "show critical CVEs affecting this product",
            "find known vulnerabilities for this software",
        ),
        avoid_phrasings=(
            "run a CVE inventory scan",
            "show CVE scan status",
            "find patches for CVE",
        ),
        confidence_boost=1.3,
        preferred_over_list=("search_cve_cache", "search_cve_live"),
    ),
    ToolManifest(
        tool_name="search_cve_cache",
        source="cve",
        domains=frozenset({"sre_cost_security"}),
        tags=frozenset({"cve", "security", "cache"}),
        affordance=ToolAffordance.READ,
        example_queries=(
            "search cached CVEs only",
            "show cached vulnerability data",
            "find CVEs without live lookup",
        ),
        conflicts_with=frozenset({"search_cve", "search_cve_live"}),
        conflict_note="search_cve_cache is for cache-only CVE lookups. Prefer search_cve unless the user explicitly asks to avoid live fallback.",
        preferred_over=frozenset(),
        primary_phrasings=(
            "search cached CVEs only",
            "cache-only vulnerability lookup",
            "find CVEs from cache",
        ),
        avoid_phrasings=(
            "search CVEs",
            "live CVE search",
            "sync CVE data",
        ),
        confidence_boost=1.15,
    ),
    ToolManifest(
        tool_name="search_cve_live",
        source="cve",
        domains=frozenset({"sre_cost_security"}),
        tags=frozenset({"cve", "security", "live"}),
        affordance=ToolAffordance.READ,
        example_queries=(
            "search CVEs live",
            "query live NVD data",
            "force live vulnerability lookup",
        ),
        conflicts_with=frozenset({"search_cve", "search_cve_cache"}),
        conflict_note="search_cve_live is for live-only CVE lookups. Prefer search_cve unless the user explicitly wants a fresh live query.",
        preferred_over=frozenset(),
        primary_phrasings=(
            "search CVEs live",
            "force live vulnerability search",
            "query NVD live",
        ),
        avoid_phrasings=(
            "search cached CVEs",
            "run CVE scan",
            "sync recent CVEs",
        ),
        confidence_boost=1.15,
    ),
    ToolManifest(
        tool_name="sync_cve",
        source="cve",
        domains=frozenset({"sre_cost_security"}),
        tags=frozenset({"cve", "security", "sync", "refresh"}),
        affordance=ToolAffordance.WRITE,
        example_queries=(
            "refresh CVE-2024-1234",
            "sync this CVE from live sources",
            "update cached CVE data",
        ),
        conflicts_with=frozenset({"sync_recent_cves"}),
        conflict_note="sync_cve refreshes one specific CVE. Use sync_recent_cves for a batch refresh window.",
        preferred_over=frozenset(),
        requires_confirmation=False,
        primary_phrasings=(
            "sync this CVE",
            "refresh CVE data",
            "update vulnerability record",
        ),
        avoid_phrasings=(
            "sync recent CVEs",
            "search CVEs",
            "scan inventory for vulnerabilities",
        ),
        confidence_boost=1.1,
    ),
    ToolManifest(
        tool_name="sync_recent_cves",
        source="cve",
        domains=frozenset({"sre_cost_security"}),
        tags=frozenset({"cve", "security", "sync", "batch"}),
        affordance=ToolAffordance.WRITE,
        example_queries=(
            "sync CVEs updated in the last 24 hours",
            "refresh recent CVE feed",
            "batch sync vulnerabilities",
        ),
        conflicts_with=frozenset({"sync_cve"}),
        conflict_note="sync_recent_cves performs a batch refresh of recent CVEs. Use sync_cve for a single CVE ID.",
        preferred_over=frozenset(),
        requires_confirmation=False,
        primary_phrasings=(
            "sync recent CVEs",
            "refresh vulnerability feed",
            "batch sync latest CVEs",
        ),
        avoid_phrasings=(
            "sync CVE-2024-1234",
            "search CVEs",
            "show cache stats",
        ),
        confidence_boost=1.1,
    ),
    ToolManifest(
        tool_name="get_cve_cache_stats",
        source="cve",
        domains=frozenset({"sre_cost_security"}),
        tags=frozenset({"cve", "cache", "stats"}),
        affordance=ToolAffordance.READ,
        example_queries=(
            "show CVE cache stats",
            "how many CVEs are cached",
            "display vulnerability cache metrics",
        ),
        conflicts_with=frozenset(),
        conflict_note="",
        preferred_over=frozenset(),
        primary_phrasings=(
            "show CVE cache stats",
            "CVE cache metrics",
            "how many vulnerabilities are cached",
        ),
        confidence_boost=1.05,
    ),
    ToolManifest(
        tool_name="scan_inventory",
        source="cve",
        domains=frozenset({"sre_cost_security", "arc_inventory"}),
        tags=frozenset({"cve", "security", "scan", "inventory", "vm"}),
        affordance=ToolAffordance.WRITE,
        example_queries=(
            "scan my VM inventory for CVEs",
            "run vulnerability scan across servers",
            "check inventory for known CVEs",
        ),
        conflicts_with=frozenset({"get_cve_scan_status", "list_cve_scans"}),
        conflict_note="scan_inventory starts a new CVE scan job. Use get_cve_scan_status for one scan ID or list_cve_scans to inspect previous scans.",
        preferred_over=frozenset(),
        requires_confirmation=False,
        primary_phrasings=(
            "scan inventory for CVEs",
            "run vulnerability scan",
            "check my servers for CVEs",
            "start CVE inventory scan",
        ),
        avoid_phrasings=(
            "show scan status",
            "list prior scans",
            "search for a specific CVE",
        ),
        confidence_boost=1.25,
    ),
    ToolManifest(
        tool_name="get_cve_scan_status",
        source="cve",
        domains=frozenset({"sre_cost_security", "arc_inventory"}),
        tags=frozenset({"cve", "scan", "status"}),
        affordance=ToolAffordance.READ,
        example_queries=(
            "show CVE scan status",
            "check if vulnerability scan finished",
            "get status of scan job",
        ),
        conflicts_with=frozenset({"list_cve_scans", "scan_inventory"}),
        conflict_note="get_cve_scan_status checks one specific scan ID. Use list_cve_scans when the user wants a recent-scan list.",
        preferred_over=frozenset(),
        primary_phrasings=(
            "show CVE scan status",
            "check vulnerability scan progress",
            "get scan job status",
        ),
        avoid_phrasings=(
            "run vulnerability scan",
            "list prior scans",
            "show affected VMs for a CVE",
        ),
        confidence_boost=1.15,
    ),
    ToolManifest(
        tool_name="list_cve_scans",
        source="cve",
        domains=frozenset({"sre_cost_security", "arc_inventory"}),
        tags=frozenset({"cve", "scan", "history"}),
        affordance=ToolAffordance.READ,
        example_queries=(
            "list recent CVE scans",
            "show previous vulnerability scans",
            "what scans have run recently",
        ),
        conflicts_with=frozenset({"get_cve_scan_status"}),
        conflict_note="list_cve_scans lists recent scan jobs. Use get_cve_scan_status when the user provides a specific scan ID.",
        preferred_over=frozenset(),
        primary_phrasings=(
            "list recent CVE scans",
            "show prior vulnerability scans",
            "what scan jobs ran recently",
        ),
        avoid_phrasings=(
            "show CVE scan status",
            "run vulnerability scan",
        ),
        confidence_boost=1.1,
    ),
    ToolManifest(
        tool_name="get_cve_affected_vms",
        source="cve",
        domains=frozenset({"sre_cost_security", "arc_inventory"}),
        tags=frozenset({"cve", "affected_vms", "inventory", "impact"}),
        affordance=ToolAffordance.READ,
        example_queries=(
            "which VMs are affected by CVE-2024-1234",
            "show servers impacted by this CVE",
            "list affected machines for a vulnerability",
        ),
        conflicts_with=frozenset({"get_patches"}),
        conflict_note="get_cve_affected_vms identifies impacted machines. Use get_patches when the user wants patch guidance for the CVE.",
        preferred_over=frozenset(),
        primary_phrasings=(
            "which VMs are affected by this CVE",
            "show impacted servers",
            "list affected machines for CVE",
        ),
        avoid_phrasings=(
            "find patches for this CVE",
            "run vulnerability scan",
        ),
        confidence_boost=1.2,
    ),
    ToolManifest(
        tool_name="resolve_kb_to_cves",
        source="cve",
        domains=frozenset({"sre_cost_security"}),
        tags=frozenset({"cve", "kb", "patch", "mapping"}),
        affordance=ToolAffordance.READ,
        example_queries=(
            "which CVEs map to KB5075999",
            "resolve KB to vulnerabilities",
            "find CVEs fixed by this KB",
        ),
        conflicts_with=frozenset({"get_patches"}),
        conflict_note="resolve_kb_to_cves maps a KB article to CVE IDs. Use get_patches when starting from a CVE and looking for remediation details.",
        preferred_over=frozenset(),
        primary_phrasings=(
            "which CVEs does this KB fix",
            "resolve KB to CVEs",
            "map patch KB to vulnerabilities",
        ),
        avoid_phrasings=(
            "find patches for CVE",
            "trigger remediation",
        ),
        confidence_boost=1.15,
    ),
    ToolManifest(
        tool_name="get_patches",
        source="cve",
        domains=frozenset({"sre_cost_security", "sre_remediation"}),
        tags=frozenset({"cve", "patch", "remediation", "kb"}),
        affordance=ToolAffordance.READ,
        example_queries=(
            "find patches for CVE-2024-1234",
            "what patch fixes this vulnerability",
            "show remediation options for this CVE",
        ),
        conflicts_with=frozenset({"resolve_kb_to_cves", "trigger_remediation"}),
        conflict_note="get_patches returns patch/remediation guidance for a CVE. Use trigger_remediation only when the user wants to apply patches to a specific VM.",
        preferred_over=frozenset({"trigger_remediation"}),
        primary_phrasings=(
            "find patches for this CVE",
            "what fixes this vulnerability",
            "show remediation patch for CVE",
        ),
        avoid_phrasings=(
            "apply patch to VM",
            "resolve KB to CVEs",
        ),
        confidence_boost=1.2,
        preferred_over_list=("trigger_remediation",),
    ),
    ToolManifest(
        tool_name="trigger_remediation",
        source="cve",
        domains=frozenset({"sre_remediation"}),
        tags=frozenset({"cve", "patch", "remediation", "install"}),
        affordance=ToolAffordance.WRITE,
        example_queries=(
            "remediate CVE-2024-1234 on vm-prod-01",
            "apply vulnerability patch to this server",
            "trigger patch installation for this CVE",
        ),
        conflicts_with=frozenset({"get_patches"}),
        conflict_note="trigger_remediation initiates patching on a specific VM. Use get_patches first when the user only wants to know what remediation is available.",
        preferred_over=frozenset(),
        requires_confirmation=True,
        primary_phrasings=(
            "remediate this CVE on a VM",
            "install patch for vulnerability",
            "apply CVE fix to server",
        ),
        avoid_phrasings=(
            "find patches for CVE",
            "search CVEs",
            "show affected VMs",
        ),
        confidence_boost=1.25,
    ),
]