"""Pipeline Planner — Stage 3 of the MCP orchestrator pipeline.

Given the tools selected by ToolRetriever and a grounding summary from
ResourceInventoryService, produces a structured ``ExecutionPlan``:
  - ordered steps, each with a tool name, pre-resolved parameters, and an
    affordance classification
  - explicit ``depends_on`` links between steps
  - fast-path for simple read queries (no LLM call — synthetic 1-step plan)

Design goals:
- 1 LLM call maximum (temperature=0.1, strict JSON output)
- Fast-path: ``is_simple_read_query()`` → synthetic 1-step plan, <1ms
- Grounding injected as compact structured JSON (not a text blob)
- Graceful degradation: if LLM unavailable, emit 1-step "ask legacy" plan

Usage::

    planner = Planner()
    plan = await planner.plan(query, retrieval_result, grounding_summary)
    for step in plan.steps:
        print(step.tool_name, step.params, step.affordance)
"""
from __future__ import annotations

import json
import logging
import os
import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)


def _extract_completion_text(raw: Any) -> str:
    """Extract text from Azure/OpenAI chat completion responses."""
    try:
        choices = getattr(raw, "choices", None) or []
        if not choices:
            return ""

        message = getattr(choices[0], "message", None)
        content = getattr(message, "content", "") if message is not None else ""

        if isinstance(content, str):
            return content
        if isinstance(content, list):
            parts: List[str] = []
            for item in content:
                if isinstance(item, str):
                    parts.append(item)
                    continue
                if isinstance(item, dict):
                    text = item.get("text")
                    if isinstance(text, str):
                        parts.append(text)
                    elif isinstance(text, dict) and isinstance(text.get("value"), str):
                        parts.append(text["value"])
                    continue
                obj_text = getattr(item, "text", None)
                if isinstance(obj_text, str):
                    parts.append(obj_text)
                elif isinstance(obj_text, dict) and isinstance(obj_text.get("value"), str):
                    parts.append(obj_text["value"])
            return "\n".join(parts)
    except Exception:
        return ""
    return ""

# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------

try:
    from app.agentic.eol.utils.tool_manifest_index import ToolAffordance
    from app.agentic.eol.utils.tool_retriever import ToolRetrievalResult
    from app.agentic.eol.utils.resource_inventory_service import GroundingSummary
except ModuleNotFoundError:
    from utils.tool_manifest_index import ToolAffordance  # type: ignore[import-not-found]
    from utils.tool_retriever import ToolRetrievalResult  # type: ignore[import-not-found]
    from utils.resource_inventory_service import GroundingSummary  # type: ignore[import-not-found]


@dataclass
class PlanStep:
    """A single step in an execution plan."""

    step_id: str
    """e.g. "step_1", "step_2" — used in depends_on references."""

    tool_name: str
    """MCP tool name to call (empty string = "legacy_react" for fallback)."""

    params: Dict[str, Any] = field(default_factory=dict)
    """Pre-resolved parameters.  Values may be placeholders (``"<resource_group>"``).
    Executor will further resolve them via ResourceInventoryService."""

    depends_on: List[str] = field(default_factory=list)
    """step_id values that must complete before this step can run."""

    affordance: ToolAffordance = ToolAffordance.READ
    """Mutability classification — drives the destructive gate in Verifier."""

    rationale: str = ""
    """Human-readable reason the Planner chose this step (for tracing/debug)."""

    is_parallel: bool = False
    """True when this step can run concurrently with other is_parallel steps."""


@dataclass
class ExecutionPlan:
    """Output of Planner.plan()."""

    query: str
    """Original user query (preserved verbatim)."""

    steps: List[PlanStep] = field(default_factory=list)
    """Ordered execution steps."""

    is_fast_path: bool = False
    """True when plan was generated by fast-path (no LLM call)."""

    conflict_notes: str = ""
    """Tool disambiguation notes injected from ToolManifestIndex."""

    planner_version: str = "1.0"
    """For traceability in logs."""

    def to_dict(self) -> Dict[str, Any]:
        """Serialise to a plain dict (for SSE events / logging)."""
        return {
            "query": self.query,
            "is_fast_path": self.is_fast_path,
            "steps": [
                {
                    "step_id": s.step_id,
                    "tool_name": s.tool_name,
                    "params": s.params,
                    "depends_on": s.depends_on,
                    "affordance": s.affordance.value,
                    "rationale": s.rationale,
                    "is_parallel": s.is_parallel,
                }
                for s in self.steps
            ],
            "conflict_notes": self.conflict_notes,
            "planner_version": self.planner_version,
        }


# ---------------------------------------------------------------------------
# Fast-path detection
# ---------------------------------------------------------------------------

# Tools that are meta/utility and should NEVER be chosen by the fast-path
# heuristic regardless of their retrieval rank.  The LLM is required to
# decide when these are appropriate.
_FAST_PATH_BLOCKED_TOOLS: frozenset = frozenset({
    # ---- Azure MCP utility meta-tools (require 'command'/'learn' arg) ----
    "documentation", "learn", "help", "feedback", "version",
    # ---- CLI scaffolding ----
    "azd",   # Azure Developer CLI
    "az",    # raw Azure CLI passthrough
    # ---- Azure MCP SERVICE CATEGORY wrappers ----
    # These are group/namespace tools that return "command required" when called
    # without a sub-command argument.  They are never the correct direct tool
    # for a read query — real list/get tools have underscores (e.g. subscription_list).
    "role", "deploy", "get_azure_bestpractices",
    "compute",           # group: VMs, VMSS etc — use virtual_machine_list etc.
    "virtualdesktop",   # group: AVD
    "appconfig",        # group: App Configuration
    "aks",              # group: Kubernetes
    "containerapp",     # group: Container Apps namespace
    "containerapps",    # group: Container Apps namespace
    "applens",          # group: App Lens diagnostics
    "appservice",       # group: App Service
    "datadog",          # group: Datadog integration
    "managedlustre",    # group: Managed Lustre
    "azuremigrate",     # group: Azure Migrate
    "azureterraformbestpractices",  # doc lookup
    "network",          # group: generic network namespace (not the network MCP source)
    "keyvault",         # group: Key Vault namespace
    "sql",              # group: SQL namespace
    "cosmosdb",         # group: Cosmos DB namespace
    "monitor",          # group: Monitor namespace (different from monitor MCP source)
    "security",         # group: Security Center namespace
    "policy",           # group: Azure Policy namespace
    "billing",          # group: Billing namespace
    "advisor",          # group: Azure Advisor namespace
    # Meta/utility tools — should never be selected by fast-path heuristic
    "describe_capabilities",
    # Network action tools — require specific src/dst params, never valid for list queries
    "test_network_connectivity",
    "check_dns_resolution",
    # Network assessment/analysis tools — complex multi-param; require LLM planning
    "assess_network_security_posture",
    "analyze_route_path",
    "simulate_nsg_flow",
    "generate_connectivity_matrix",
    "analyze_private_connectivity_coverage",
    "analyze_dns_resolution_path",
})

_FAST_PATH_PATTERNS = re.compile(
    r"""
    ^\s*(?:
        (?:list|show|get|display|fetch|find|describe|enumerate)\s
        |what\s+(?:are|is)\s+(?:my|the)\s
        |(?:how\s+many)\s
        |summarize\s
    )
    """,
    re.IGNORECASE | re.VERBOSE,
)

_MULTI_STEP_KEYWORDS = re.compile(
    r"\b(?:then|after(?:\s+that)?|also|and\s+then|followed\s+by|next|finally|"
    r"restart|remediat|fix|updat|deploy|delet|creat|scale|assign|enable|disable)\b",
    re.IGNORECASE,
)


def is_simple_read_query(query: str) -> bool:
    """Return True when the query is a single-step, read-only lookup.

    Fast-path heuristic — avoids an LLM call for ≥60% of production queries.
    Conservative: returns False whenever a multi-step keyword is detected, even
    if the base pattern matches (e.g. "list my VMs then restart the failed one").

    Args:
        query: Raw user query string.

    Returns:
        True only when it is safe to skip the planner LLM call.
    """
    if _MULTI_STEP_KEYWORDS.search(query):
        return False
    return bool(_FAST_PATH_PATTERNS.match(query.strip()))


# Stop-words not useful for tool matching
_STOP_WORDS = frozenset({
    "a", "an", "the", "my", "our", "your", "its", "their",
    "i", "me", "we", "you", "he", "she", "it", "they",
    "is", "are", "was", "were", "be", "been", "being",
    "have", "has", "had", "do", "does", "did", "will",
    "would", "could", "should", "can", "may", "might",
    "in", "on", "at", "by", "for", "of", "to", "from",
    "with", "about", "into", "through", "during",
    "all", "any", "both", "each", "few", "more", "most",
    "other", "some", "such", "no", "not", "only", "own",
    "same", "so", "than", "too", "very", "and", "or", "but",
    "what", "which", "who", "that", "this", "these", "those",
    "show", "list", "get", "display", "fetch", "find",
    "describe", "enumerate", "how", "many",
})


def _pick_fast_path_tool(query: str, tool_names: List[str]) -> Optional[str]:
    """Return the best tool name for a fast-path read query, or *None* to fall
    through to the LLM planner.

    Selection rules (in priority order):
    1. Blocked tool names (``documentation``, ``learn``, etc.) are never chosen.
    2. Score each candidate by keyword overlap: split the query and tool name
       into tokens and count how many query tokens appear in the tool name.
    3. Return the highest-scoring tool **only** if its score > 0.
    4. Return *None* when no keyword overlap exists — this forces the LLM path
       so it can make a smarter choice.

    Args:
        query:      Raw user query string.
        tool_names: Ordered list of candidate tool names from retrieval.

    Returns:
        Best tool name, or None.
    """
    # Filter out blocked tools
    candidates = [t for t in tool_names if t.lower() not in _FAST_PATH_BLOCKED_TOOLS]
    if not candidates:
        return None

    # Tokenise query: lowercase words minus stop-words
    query_tokens = {
        w for w in re.findall(r"[a-z]+", query.lower())
        if w not in _STOP_WORDS and len(w) > 2
    }

    # Expand common Azure abbreviations so 'virtual'+'network' → also matches 'vnet',
    # 'virtual'+'machine' → 'vm', 'network'+'security' → 'nsg', etc.
    if "virtual" in query_tokens and ("network" in query_tokens or "networks" in query_tokens):
        query_tokens.add("vnet")
    if "virtual" in query_tokens and ("machine" in query_tokens or "machines" in query_tokens):
        query_tokens.add("vm")
    if "network" in query_tokens and "security" in query_tokens:
        query_tokens.add("nsg")
    if "resource" in query_tokens and "group" in query_tokens:
        query_tokens.add("rg")
    # Reverse-expand: abbreviated forms → full token set so specialised list
    # tools (e.g. virtual_network_list) out-score generic inspect tools
    if "vnet" in query_tokens or "vnets" in query_tokens:
        query_tokens.add("virtual")
        query_tokens.add("network")
    if "vm" in query_tokens or "vms" in query_tokens:
        query_tokens.add("virtual")
        query_tokens.add("machine")
    if "nsg" in query_tokens or "nsgs" in query_tokens:
        query_tokens.add("network")
        query_tokens.add("security")
    if "container" in query_tokens and ("app" in query_tokens or "apps" in query_tokens):
        query_tokens.add("containerapp")
        query_tokens.add("containerapps")

    if not query_tokens:
        # No meaningful tokens — use first non-blocked candidate (keeps old
        # behaviour for very short / single-word queries)
        return candidates[0]

    best_name: Optional[str] = None
    best_score: int = 0

    for name in candidates:
        # Tokenise the tool name by splitting on _ and - so that 'virtual'
        # matches 'virtual_network_list' but NOT 'virtualdesktop'.
        tool_tokens = set(re.findall(r"[a-z0-9]+", name.lower()))
        score = 0
        for qt in query_tokens:
            variants = {qt}
            if qt.endswith("s") and len(qt) > 3:
                variants.add(qt[:-1])   # subscriptions → subscription
            else:
                variants.add(qt + "s")  # subscription → subscriptions
            if any(v in tool_tokens for v in variants):
                score += 1
        if score > best_score:
            best_score = score
            best_name = name

    # Only fast-path if at least one keyword matched; otherwise defer to LLM
    return best_name if best_score > 0 else None


# ---------------------------------------------------------------------------
# Action-query fast-path — deterministic tool selection for explicit actions
# ---------------------------------------------------------------------------

# Ordered list of (pattern, tool_name) pairs.  The first pattern that matches
# the query AND whose tool_name is in the candidate tool list wins.
_ACTION_PATTERNS: List[Tuple[re.Pattern, str]] = [
    # Network connectivity test
    (re.compile(r"\btest\s+(?:network\s+)?connect(?:ivity)?", re.I), "test_network_connectivity"),
    # DNS resolution check
    (re.compile(r"\bcheck\s+dns\b", re.I), "check_dns_resolution"),
    (re.compile(r"\bdns\s+resolut", re.I), "check_dns_resolution"),
    (re.compile(r"\bresolv(?:e|ing)\s+(?:dns|domain)", re.I), "check_dns_resolution"),
    # NSG listing — list/show/get/enumerate NSGs
    (re.compile(r"\b(?:list|show|get|display|enumerate)\s+(?:(?:my|all|the)\s+)?(?:nsg|nsgs|network\s+security\s+groups?)", re.I), "nsg_list"),
    (re.compile(r"\b(?:nsg|nsgs|network\s+security\s+groups?)\s+(?:in|for|within)", re.I), "nsg_list"),
    (re.compile(r"\bwhat\s+(?:nsg|nsgs|network\s+security\s+groups?)\s+(?:do|are|exist)", re.I), "nsg_list"),
    # NSG rule inspection (specific NSG)
    (re.compile(r"\bcheck\s+(?:nsg|network\s+security\s+group)\s+rules?", re.I), "inspect_nsg_rules"),
    (re.compile(r"\b(?:show|inspect|get)\s+(?:nsg\s+)?rules?\s+for\b", re.I), "inspect_nsg_rules"),
    (re.compile(r"\brules?\s+(?:in|for|of)\s+(?:my\s+)?(?:nsg|network\s+security\s+group)", re.I), "inspect_nsg_rules"),
    # Private endpoint listing
    (re.compile(r"\b(?:list|show|get|display|enumerate)\s+(?:(?:my|all|the)\s+)?private\s+endpoints?", re.I), "private_endpoint_list"),
    (re.compile(r"\bwhat\s+private\s+endpoints?\s+(?:do|are|exist)", re.I), "private_endpoint_list"),
    # Network resource inventory
    (re.compile(r"\binventor(?:y|ize)\s+(?:my\s+|all\s+)?network\s+resources?", re.I), "inventory_network_resources"),
    (re.compile(r"\bnetwork\s+resource\s+inventor(?:y|ize)", re.I), "inventory_network_resources"),
    # Hub-spoke topology validation
    (re.compile(r"\bvalidate\s+(?:my\s+|the\s+)?hub[- ]spoke\s+topolog", re.I), "validate_hub_spoke_topology"),
    (re.compile(r"\bhub[- ]spoke\s+(?:topolog|architect|health|validat)", re.I), "validate_hub_spoke_topology"),
    # VPN / ExpressRoute inspection
    (re.compile(r"\b(?:check|show|inspect)\s+(?:my\s+)?vpn\s+gateway", re.I), "inspect_vpn_expressroute"),
    (re.compile(r"\bexpressroute\s+circuit\s+(?:state|status|health)", re.I), "inspect_vpn_expressroute"),
    # App Gateway / WAF
    (re.compile(r"\b(?:check|show|inspect)\s+(?:application\s+gateway|appgw|app\s+gw)", re.I), "inspect_appgw_waf"),
    (re.compile(r"\b(?:show|inspect)\s+waf\s+polic", re.I), "inspect_appgw_waf"),
    # Effective route lookup
    (re.compile(r"\bcheck\s+(?:effective\s+)?routes?\b", re.I), "get_effective_routes"),
    (re.compile(r"\b(?:show|get)\s+effective\s+(?:routes?|nsg\s+rules?)", re.I), "get_effective_routes_and_rules"),
]


def _pick_action_tool(query: str, tool_names: List[str]) -> Optional[str]:
    """Return an action tool for explicit action queries, or *None* to fall through.

    Scans ``_ACTION_PATTERNS`` in order; returns the first matching tool that
    is present in *tool_names*.  Returns *None* when no pattern matches or
    the matching tool is not available in the retrieved set.
    """
    tool_set = set(tool_names)
    for pattern, tool_name in _ACTION_PATTERNS:
        if pattern.search(query) and tool_name in tool_set:
            return tool_name
    return None


def _pick_list_intent_override(query: str, tool_names: List[str]) -> Optional[Tuple[str, Dict[str, Any], str]]:
    """Return deterministic fast-path override for high-confidence list intents."""
    q = query.lower()
    is_list_intent = bool(re.search(r"\b(show|list|get|display|enumerate|what\s+are)\b", q))

    if not is_list_intent:
        return None

    # Do not collapse performance/utilization queries into a list-only tool.
    # Example: "show CPU and memory utilization of these VMs" should run a
    # list + metrics sequence, not just virtual_machine_list.
    vm_intent = bool(re.search(r"\bvirtual\s*machines?\b|\bvms?\b", q, re.I))
    perf_intent = bool(
        re.search(
            r"\b(cpu|memory|utili[sz]ation|performance|metric(?:s)?|usage|trend(?:s)?)\b",
            q,
            re.I,
        )
    )
    if vm_intent and perf_intent:
        return None

    available = set(tool_names)

    # Manifest-aligned list/discovery intents (prefer explicit list tools)
    list_rules: List[Tuple[re.Pattern, List[str], str]] = [
        (
            re.compile(r"\bcontainer\s*apps?\b|\bcontainerapps?\b", re.I),
            ["container_app_list", "azure_cli_execute_command"],
            "Container Apps list",
        ),
        (
            re.compile(r"\bvirtual\s*machines?\b|\bvms?\b", re.I),
            ["virtual_machine_list"],
            "Virtual Machines list",
        ),
        (
            re.compile(r"\bstorage\s*accounts?\b", re.I),
            ["storage_account_list"],
            "Storage Accounts list",
        ),
        (
            re.compile(r"\bvirtual\s*networks?\b|\bvnets?\b", re.I),
            ["virtual_network_list"],
            "Virtual Networks list",
        ),
        (
            re.compile(r"\bprivate\s*endpoints?\b", re.I),
            ["private_endpoint_list"],
            "Private Endpoints list",
        ),
        (
            re.compile(r"\bnetwork\s*security\s*groups?\b|\bnsgs?\b", re.I),
            ["nsg_list"],
            "Network Security Groups list",
        ),
        (
            re.compile(r"\bresource\s*groups?\b", re.I),
            ["groups"],
            "Resource Groups list",
        ),
        (
            re.compile(r"\bsubscriptions?\b", re.I),
            ["subscriptions"],
            "Subscriptions list",
        ),
        (
            re.compile(r"\bsecurity\s*recommendations?\b", re.I),
            ["list_security_recommendations"],
            "Security recommendations list",
        ),
    ]

    for pattern, preferred_tools, label in list_rules:
        if not pattern.search(q):
            continue
        for preferred in preferred_tools:
            if preferred in available:
                if preferred == "azure_cli_execute_command":
                    return (
                        preferred,
                        {"command": "az containerapp list --output json"},
                        f"List-intent override: {label} via Azure CLI fallback.",
                    )
                return (
                    preferred,
                    {},
                    f"List-intent override: {label}.",
                )

    return None


def _pick_vm_metrics_sequence(
    query: str,
    tool_names: List[str],
) -> Optional[List[PlanStep]]:
    """Return deterministic two-step plan for VM CPU/memory utilization intents.

    Sequence:
    1) virtual_machine_list
    2) get_performance_metrics (resource_id fan-out from step_1 virtual_machines[*])
    """
    q = query.lower()
    has_vm_intent = bool(re.search(r"\bvirtual\s*machines?\b|\bvms?\b", q, re.I))
    has_perf_intent = bool(
        re.search(
            r"\b(cpu|memory|utili[sz]ation|performance|metric(?:s)?|usage|trend(?:s)?)\b",
            q,
            re.I,
        )
    )
    if not (has_vm_intent and has_perf_intent):
        return None

    available = set(tool_names)
    if "virtual_machine_list" not in available or "get_performance_metrics" not in available:
        return None

    return [
        PlanStep(
            step_id="step_1",
            tool_name="virtual_machine_list",
            params={},
            affordance=ToolAffordance.READ,
            rationale="VM metrics sequence: discover VMs before querying utilization metrics.",
            is_parallel=False,
        ),
        PlanStep(
            step_id="step_2",
            tool_name="get_performance_metrics",
            params={
                "resource_id": "$step_1.virtual_machines[*].resource_id",
                "metric_names": ["Percentage CPU", "Available Memory Bytes"],
            },
            depends_on=["step_1"],
            affordance=ToolAffordance.READ,
            rationale="VM metrics sequence: retrieve CPU and memory metrics for each discovered VM.",
            is_parallel=False,
        ),
    ]


def _pick_container_app_health_sequence(
    query: str,
    tool_names: List[str],
) -> Optional[List[PlanStep]]:
    """Return deterministic two-step plan for container app health intents.

    Sequence:
    1) container_app_list
    2) check_container_app_health (resource_id from step_1 apps[0].id)

    This handles prompts like "show health of my container apps" where a
    single-tool list response is insufficient.
    """
    q = query.lower()
    has_container_app_intent = bool(re.search(r"\bcontainer\s*apps?\b|\bcontainerapps?\b", q, re.I))
    has_health_intent = bool(re.search(r"\b(health|healthy|status|degraded|unhealthy|availability)\b", q, re.I))
    if not (has_container_app_intent and has_health_intent):
        return None

    available = set(tool_names)
    if "container_app_list" not in available or "check_container_app_health" not in available:
        return None

    return [
        PlanStep(
            step_id="step_1",
            tool_name="container_app_list",
            params={},
            affordance=ToolAffordance.READ,
            rationale="Container App health sequence: discover apps first.",
            is_parallel=False,
        ),
        PlanStep(
            step_id="step_2",
            tool_name="check_container_app_health",
            params={
                "resource_id": "$step_1.apps[0].id",
            },
            depends_on=["step_1"],
            affordance=ToolAffordance.READ,
            rationale=(
                "Container App health sequence: run SRE health check using the discovered app resource_id."
            ),
            is_parallel=False,
        ),
    ]


# ---------------------------------------------------------------------------
# JSON schema the planner asks the LLM to produce
# ---------------------------------------------------------------------------

_PLAN_JSON_SCHEMA = {
    "type": "object",
    "required": ["steps"],
    "properties": {
        "steps": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["step_id", "tool_name", "params", "depends_on", "rationale"],
                "properties": {
                    "step_id":    {"type": "string"},
                    "tool_name":  {"type": "string"},
                    "params":     {"type": "object"},
                    "depends_on": {"type": "array", "items": {"type": "string"}},
                    "rationale":  {"type": "string"},
                    "is_parallel": {"type": "boolean"},
                },
            },
        }
    },
}


def _build_planner_system_prompt() -> str:
    return """You are the Azure operations Planner.

Given a user query, a set of available tools, and an environment grounding summary,
output a JSON execution plan with the following schema:

{
  "steps": [
    {
      "step_id": "step_1",
      "tool_name": "<exact tool name from the available list>",
      "params": { "<param>": "<value or placeholder>" },
      "depends_on": [],
      "rationale": "<one sentence>",
      "is_parallel": false
    }
  ]
}

Rules:
1. Use ONLY tool names from the AVAILABLE TOOLS list.
2. Scope params (subscription_id, resource_group) MUST only be filled when the user
   EXPLICITLY mentions them in the query OR when the exact resource appears in RESOURCE INVENTORY.
   NEVER infer scope params from the GROUNDING SUMMARY counts alone.
   If a scope param is not explicitly stated and not in RESOURCE INVENTORY, omit it entirely.
3. For resource name params (e.g. resource_id, name): if the user's query refers to a resource
   that appears in RESOURCE INVENTORY, use the exact name listed there — do NOT use a placeholder.
   Use placeholder strings like "<resource_id>" ONLY for resources the user referenced but that
   are NOT found in RESOURCE INVENTORY.
4. Set is_parallel=true for steps with no depends_on that can run concurrently.
5. Do NOT add a "response_compose" step — that is handled separately.
6. Output ONLY valid JSON — no markdown fences, no prose.
7. Minimum 1 step, maximum 5 steps.
8. If the query needs only one tool call, output a single step.
9. If a step modifies Azure state, mark its params with a "_destructive": true field.
10. Azure CLI two-step rule: if azmcp_extension_cli_generate is in the AVAILABLE TOOLS list,
    you MUST use it as step 1 before azure_cli_execute_command:
      step 1 → azmcp_extension_cli_generate  params: {intent: "<natural language goal>", cliType: "az"}
      step 2 → azure_cli_execute_command      params: {command: "$step_1._generated_command"}
    This ensures the correct az command with proper --query paths is generated by Azure's CLI Copilot.
    If azmcp_extension_cli_generate is NOT listed in AVAILABLE TOOLS, write the az command directly.

Multi-step guidance:
- Use multiple steps when the query requires aggregating data from multiple sources
  (e.g. "show my VNets and their NSGs" → virtual_network_list + nsg_list in parallel).
- Use depends_on when step B needs the result of step A to resolve a parameter
  (e.g. "show rules for each NSG in rg-prod" → list step first, then inspect step).
- For a list-then-detail pattern, step 1 is the list tool with no resource_id,
  step 2 targets a specific resource and sets depends_on=["step_1"]; the composer
  will iterate over step 1's results to drive step 2's context.
- Independent enrichment steps (no data dependency) should use is_parallel=true.

Step output references:
- When step B depends on step A and needs a value from step A's result, use the
  reference syntax "$step_A.path[idx].field" as the param value.
  Examples:
    "subscription_id": "$step_1.subscriptions[0].subscription_id"
    "resource_id": "$step_1.virtual_networks[0].resource_id"
        "resource_id": "$step_1.network_security_groups[0].resource_id"
    "resource_group": "$step_1.network_security_groups[0].resource_group"
- Only use step-refs for params that genuinely require a value from a prior step.
  For params that have sensible defaults (e.g. subscription_id reads from env),
  omit them entirely rather than chaining unnecessarily.

Azure CLI --query JMESPath reference (use these exact paths — do NOT guess):
  Private endpoint:
    IP address (DNS)       → --query 'customDnsConfigs[].ipAddresses[]'
                             ⚠️  EMPTY when endpoint is linked to a private DNS zone.
                             In that case use private_endpoint_list tool (NIC-aware) or two-step NIC lookup.
    IP via NIC (step 1)    → --query 'networkInterfaces[0].id' -o tsv  (then az network nic show --ids <id>)
    IP via NIC (step 2)    → az network nic show --ids <nic_id> --query 'ipConfigurations[0].privateIPAddress'
    Connection status      → --query 'privateLinkServiceConnections[0].privateLinkServiceConnectionState.status'
    Provisioning state     → --query 'provisioningState'
    Subnet                 → --query 'subnet.id'
  Virtual machine:
    Private IP             → az network nic show --ids <nicId> --query 'ipConfigurations[0].privateIPAddress'
    Public IP              → az network public-ip show --ids <publicIpId> --query 'ipAddress'
    Power state            → az vm get-instance-view --query 'instanceView.statuses[1].displayStatus'
    NIC IDs                → az vm show --query 'networkProfile.networkInterfaces[].id'
  Virtual network / subnet:
    Address prefixes       → --query 'addressSpace.addressPrefixes'
    Subnets                → --query 'subnets[].{name:name, prefix:addressPrefix}'
  NSG:
    Security rules         → --query 'securityRules[].{name:name,priority:priority,direction:direction,access:access,protocol:protocol,src:sourceAddressPrefix,dst:destinationAddressPrefix,dstPort:destinationPortRange}'
  Storage account:
    Blob endpoint          → --query 'primaryEndpoints.blob'
    Connection string      → az storage account show-connection-string --query 'connectionString'
  Key Vault:
    Vault URI              → --query 'properties.vaultUri'
    Network ACLs           → --query 'properties.networkAcls'
  App Service / Function:
    Outbound IPs           → --query 'outboundIpAddresses'
    Inbound IP             → --query 'inboundIpAddress'
  Container App:
    Ingress FQDN           → --query 'properties.configuration.ingress.fqdn'
    Provisioning state     → --query 'properties.provisioningState'
"""


def _build_planner_user_prompt(
    query: str,
    tool_names: List[str],
    grounding_summary: Optional[GroundingSummary],
    conflict_notes: str,
    inventory_context: str = "",
) -> str:
    grounding_dict: Dict[str, Any] = {}
    if grounding_summary:
        grounding_dict = {
            "tenant_id": grounding_summary.tenant_id,
            "subscriptions": grounding_summary.subscriptions,
            "resource_groups": grounding_summary.resource_groups[:10],
            "resource_type_counts": grounding_summary.resource_type_counts,
        }

    parts = [
        f"USER QUERY: {query}",
        "",
        f"AVAILABLE TOOLS ({len(tool_names)}):",
        *[f"  - {name}" for name in tool_names],
        "",
        f"GROUNDING SUMMARY:\n{json.dumps(grounding_dict, indent=2)}",
    ]
    if inventory_context:
        parts += [
            "",
            "RESOURCE INVENTORY (use these exact resource names in params — do NOT use placeholders if the resource is listed here):",
            inventory_context,
        ]
    if conflict_notes:
        parts += ["", f"TOOL DISAMBIGUATION NOTES:\n{conflict_notes}"]

    parts += ["", "Output the JSON execution plan now:"]
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Planner class
# ---------------------------------------------------------------------------


class Planner:
    """Pipeline Planner — produces an ExecutionPlan from a query + tool set.

    Usage::

        planner = Planner()
        plan = await planner.plan(
            query="check health of prod-api",
            retrieval_result=result,
            grounding_summary=summary,
        )
    """

    def __init__(
        self,
        manifest_index: Optional[Any] = None,
    ) -> None:
        """Initialise the Planner.

        Args:
            manifest_index: Optional ``ToolManifestIndex`` for affordance lookup.
                If None, affordance defaults to READ for all steps.
        """
        self._manifest_index = manifest_index

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    async def plan(
        self,
        query: str,
        retrieval_result: ToolRetrievalResult,
        grounding_summary: Optional[GroundingSummary] = None,
        inventory_context: str = "",
    ) -> ExecutionPlan:
        """Produce an ``ExecutionPlan`` for *query*.

        Fast-path:
            If ``is_simple_read_query(query)`` and ``retrieval_result`` has
            exactly one candidate tool, returns a synthetic 1-step plan without
            an LLM call.

        LLM path:
            Calls Azure OpenAI with a structured JSON prompt (temperature=0.1)
            and parses the response into ``PlanStep`` objects.

        Fallback:
            If the LLM is unavailable or returns invalid JSON, emits a single
            "legacy_react" step so the orchestrator can fall back to the ReAct
            loop.

        Args:
            query: Raw user query string.
            retrieval_result: Output of ``ToolRetriever.retrieve()``.
            grounding_summary: Optional ``GroundingSummary`` from
                ``ResourceInventoryService.get_grounding_summary()``.

        Returns:
            ``ExecutionPlan`` — always non-empty (at least one step).
        """
        tools = retrieval_result.tools
        conflict_notes = retrieval_result.conflict_notes
        all_tool_names = [
            t.get("function", {}).get("name", "") for t in tools if t.get("function")
        ]
        # Strip meta / namespace-group tools so neither fast-path nor LLM picks them.
        # Note: action tools (test_*, check_*) are NOT stripped here — they are
        # excluded from the _pick_fast_path_tool read-path by _FAST_PATH_BLOCKED_TOOLS
        # but must remain available for the action fast-path and the LLM planner.
        tool_names = [t for t in all_tool_names if t.lower() not in _FAST_PATH_BLOCKED_TOOLS]

        # ── Action fast-path: explicit action queries (test/check) ──────
        # Uses all_tool_names so action tools excluded from the read fast-path
        # (test_network_connectivity, check_dns_resolution, etc.) are still reachable.
        if all_tool_names:
            health_sequence = _pick_container_app_health_sequence(query, all_tool_names)
            if health_sequence:
                logger.debug("⚡ Planner container-app-health sequence fast-path")
                return ExecutionPlan(
                    query=query,
                    steps=health_sequence,
                    is_fast_path=True,
                    conflict_notes=conflict_notes,
                )

            vm_metrics_sequence = _pick_vm_metrics_sequence(query, all_tool_names)
            if vm_metrics_sequence:
                logger.debug("⚡ Planner vm-metrics sequence fast-path")
                return ExecutionPlan(
                    query=query,
                    steps=vm_metrics_sequence,
                    is_fast_path=True,
                    conflict_notes=conflict_notes,
                )

            action_tool = _pick_action_tool(query, all_tool_names)
            if action_tool:
                step = PlanStep(
                    step_id="step_1",
                    tool_name=action_tool,
                    params={},
                    affordance=self._get_affordance(action_tool),
                    rationale="Action fast-path: explicit action query matched tool directly.",
                    is_parallel=False,
                )
                logger.debug("⚡ Planner action fast-path: tool=%s", action_tool)
                return ExecutionPlan(
                    query=query,
                    steps=[step],
                    is_fast_path=True,
                    conflict_notes=conflict_notes,
                )

            list_override = _pick_list_intent_override(query, all_tool_names)
            if list_override:
                override_tool, override_params, override_rationale = list_override
                step = PlanStep(
                    step_id="step_1",
                    tool_name=override_tool,
                    params=override_params,
                    affordance=self._get_affordance(override_tool),
                    rationale=override_rationale,
                    is_parallel=False,
                )
                logger.debug("⚡ Planner list-intent override: tool=%s", override_tool)
                return ExecutionPlan(
                    query=query,
                    steps=[step],
                    is_fast_path=True,
                    conflict_notes=conflict_notes,
                )

        # ── Fast-path: single read query, skip LLM call ────────────────
        logger.debug("⚡ Planner: 15 candidate tool_names=%s", tool_names)
        if tool_names and is_simple_read_query(query):
            best_tool = _pick_fast_path_tool(query, tool_names)
            if best_tool:
                step = PlanStep(
                    step_id="step_1",
                    tool_name=best_tool,
                    params={},
                    affordance=self._get_affordance(best_tool),
                    rationale="Fast-path: single-step read query.",
                    is_parallel=False,
                )
                logger.debug("⚡ Planner fast-path: tool=%s", best_tool)
                return ExecutionPlan(
                    query=query,
                    steps=[step],
                    is_fast_path=True,
                    conflict_notes=conflict_notes,
                )
            logger.debug("⚡ Planner fast-path: no keyword match for %r — falling through to LLM", query)

        # ── LLM path ───────────────────────────────────────────────────
        # Always surface azure_cli_execute_command so the LLM can use it as a
        # last-resort fallback without any explicit fast-path pattern.
        _CLI_TOOL = "azure_cli_execute_command"
        if _CLI_TOOL not in tool_names:
            tool_names.append(_CLI_TOOL)

        if not tool_names:
            logger.warning("Planner: no tools in retrieval_result; emitting legacy fallback step")
            return self._legacy_fallback_plan(query, conflict_notes)

        system_prompt = _build_planner_system_prompt()
        user_prompt = _build_planner_user_prompt(
            query, tool_names, grounding_summary, conflict_notes,
            inventory_context=inventory_context,
        )

        ok, raw_text = await self._call_llm(system_prompt, user_prompt, temperature=0.1)
        if not ok:
            logger.warning("Planner: LLM call failed; using legacy fallback plan")
            return self._legacy_fallback_plan(query, conflict_notes)

        steps = self._parse_steps(raw_text, tool_names)
        if not steps:
            logger.warning("Planner: could not parse LLM response; using legacy fallback plan")
            return self._legacy_fallback_plan(query, conflict_notes)

        logger.info(
            "📋 Planner produced %d step(s) for query (fast_path=False): %s",
            len(steps),
            [s.tool_name for s in steps],
        )
        return ExecutionPlan(
            query=query,
            steps=steps,
            is_fast_path=False,
            conflict_notes=conflict_notes,
        )

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _get_affordance(self, tool_name: str) -> ToolAffordance:
        if self._manifest_index is None:
            return ToolAffordance.READ
        return self._manifest_index.get_affordance(tool_name)

    def _legacy_fallback_plan(self, query: str, conflict_notes: str) -> ExecutionPlan:
        """Return a 1-step plan that asks the legacy ReAct loop to handle the query."""
        return ExecutionPlan(
            query=query,
            steps=[
                PlanStep(
                    step_id="step_1",
                    tool_name="legacy_react",
                    params={"query": query},
                    affordance=ToolAffordance.READ,
                    rationale="Planner fallback: no tools available or LLM error.",
                )
            ],
            is_fast_path=False,
            conflict_notes=conflict_notes,
        )

    def _parse_steps(
        self,
        raw_text: str,
        valid_tool_names: List[str],
    ) -> List[PlanStep]:
        """Parse LLM JSON response into a list of PlanStep objects.

        Returns empty list on parse failure.
        """
        # Strip optional markdown fences
        text = raw_text.strip()
        if text.startswith("```"):
            text = re.sub(r"^```(?:json)?\n?", "", text, flags=re.IGNORECASE)
            text = re.sub(r"\n?```$", "", text)

        try:
            data = json.loads(text)
        except json.JSONDecodeError as exc:
            logger.debug("Planner JSON parse error: %s | raw=%s", exc, raw_text[:200])
            return []

        raw_steps = data.get("steps") if isinstance(data, dict) else None
        if not isinstance(raw_steps, list) or not raw_steps:
            return []

        valid_name_set = set(valid_tool_names)
        steps: List[PlanStep] = []
        for i, raw in enumerate(raw_steps[:5]):  # cap at 5 steps
            if not isinstance(raw, dict):
                continue
            tool_name = raw.get("tool_name", "")
            if tool_name not in valid_name_set:
                # Try first valid tool as fallback for this step
                logger.debug(
                    "Planner: tool_name %r not in valid set; skipping step %d", tool_name, i + 1
                )
                continue
            step_id = raw.get("step_id") or f"step_{i + 1}"
            params = raw.get("params") or {}
            if not isinstance(params, dict):
                params = {}
            depends_on = raw.get("depends_on") or []
            if not isinstance(depends_on, list):
                depends_on = []
            rationale = raw.get("rationale", "")
            is_parallel = bool(raw.get("is_parallel", False))
            affordance = self._get_affordance(tool_name)
            # Override with manifest if _destructive flag present in params
            if params.pop("_destructive", False):
                affordance = ToolAffordance.DESTRUCTIVE
            steps.append(
                PlanStep(
                    step_id=str(step_id),
                    tool_name=tool_name,
                    params=params,
                    depends_on=[str(d) for d in depends_on],
                    affordance=affordance,
                    rationale=str(rationale),
                    is_parallel=is_parallel,
                )
            )

        return steps

    async def _call_llm(
        self,
        system_prompt: str,
        user_prompt: str,
        temperature: float = 0.1,
        max_tokens: int = 800,
    ) -> tuple[bool, str]:
        """Make a single LLM call (no tools).

        Returns (success, text_content).
        """
        try:
            from openai import AsyncAzureOpenAI

            endpoint = os.getenv("AZURE_OPENAI_ENDPOINT", "")
            if not endpoint:
                return False, "AZURE_OPENAI_ENDPOINT not set"

            api_key = os.getenv("AZURE_OPENAI_API_KEY")
            api_version = os.getenv("AZURE_OPENAI_API_VERSION", "2024-08-01-preview")
            deployment = (
                os.getenv("AZURE_OPENAI_CHAT_DEPLOYMENT_NAME")
                or os.getenv("AZURE_OPENAI_DEPLOYMENT", "gpt-4o-mini")
            )

            async_credential = None
            if api_key:
                client = AsyncAzureOpenAI(
                    api_key=api_key,
                    azure_endpoint=endpoint,
                    api_version=api_version,
                )
            else:
                from azure.identity.aio import (  # type: ignore[import-not-found]
                    DefaultAzureCredential as AsyncDefaultAzureCredential,
                )
                async_credential = AsyncDefaultAzureCredential(
                    exclude_interactive_browser_credential=True,
                    exclude_shared_token_cache_credential=True,
                    exclude_visual_studio_code_credential=True,
                    exclude_powershell_credential=True,
                )
                token = await async_credential.get_token(
                    "https://cognitiveservices.azure.com/.default"
                )
                client = AsyncAzureOpenAI(
                    api_key=token.token,
                    azure_endpoint=endpoint,
                    api_version=api_version,
                )

            try:
                completion_kwargs: Dict[str, Any] = {
                    "model": deployment,
                    "messages": [
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_prompt},
                    ],
                    "response_format": {"type": "json_object"},
                }
                deployment_lower = (deployment or "").lower()
                if deployment_lower.startswith("gpt-5"):
                    completion_kwargs["max_completion_tokens"] = max_tokens
                else:
                    completion_kwargs["temperature"] = temperature
                    completion_kwargs["max_tokens"] = max_tokens

                raw = await client.chat.completions.create(**completion_kwargs)
            finally:
                await client.close()
                if async_credential:
                    await async_credential.close()

            content = _extract_completion_text(raw)
            return True, content

        except Exception as exc:  # pylint: disable=broad-except
            logger.error("Planner LLM call failed: %s", exc)
            return False, str(exc)
