"""Pipeline Planner — Stage 3 of the MCP orchestrator pipeline.

Given the tools selected by ToolRetriever and a grounding summary from
ResourceInventoryService, produces a structured ``ExecutionPlan``:
  - ordered steps, each with a tool name, pre-resolved parameters, and an
    affordance classification
  - explicit ``depends_on`` links between steps
  - fast-path for simple read queries (no LLM call — synthetic 1-step plan)

Design goals:
- 1 LLM call maximum (temperature=0.1, strict JSON output)
- Fast-path: ``is_simple_read_query()`` → synthetic 1-step plan, <1ms
- Grounding injected as compact structured JSON (not a text blob)
- Graceful degradation: if LLM unavailable, emit 1-step "ask legacy" plan

Usage::

    planner = Planner()
    plan = await planner.plan(query, retrieval_result, grounding_summary)
    for step in plan.steps:
        print(step.tool_name, step.params, step.affordance)
"""
from __future__ import annotations

import json
import logging
import os
import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------

try:
    from app.agentic.eol.utils.tool_manifest_index import ToolAffordance
    from app.agentic.eol.utils.tool_retriever import ToolRetrievalResult
    from app.agentic.eol.utils.resource_inventory_service import GroundingSummary
except ModuleNotFoundError:
    from utils.tool_manifest_index import ToolAffordance  # type: ignore[import-not-found]
    from utils.tool_retriever import ToolRetrievalResult  # type: ignore[import-not-found]
    from utils.resource_inventory_service import GroundingSummary  # type: ignore[import-not-found]


@dataclass
class PlanStep:
    """A single step in an execution plan."""

    step_id: str
    """e.g. "step_1", "step_2" — used in depends_on references."""

    tool_name: str
    """MCP tool name to call (empty string = "legacy_react" for fallback)."""

    params: Dict[str, Any] = field(default_factory=dict)
    """Pre-resolved parameters.  Values may be placeholders (``"<resource_group>"``).
    Executor will further resolve them via ResourceInventoryService."""

    depends_on: List[str] = field(default_factory=list)
    """step_id values that must complete before this step can run."""

    affordance: ToolAffordance = ToolAffordance.READ
    """Mutability classification — drives the destructive gate in Verifier."""

    rationale: str = ""
    """Human-readable reason the Planner chose this step (for tracing/debug)."""

    is_parallel: bool = False
    """True when this step can run concurrently with other is_parallel steps."""


@dataclass
class ExecutionPlan:
    """Output of Planner.plan()."""

    query: str
    """Original user query (preserved verbatim)."""

    steps: List[PlanStep] = field(default_factory=list)
    """Ordered execution steps."""

    is_fast_path: bool = False
    """True when plan was generated by fast-path (no LLM call)."""

    conflict_notes: str = ""
    """Tool disambiguation notes injected from ToolManifestIndex."""

    planner_version: str = "1.0"
    """For traceability in logs."""

    def to_dict(self) -> Dict[str, Any]:
        """Serialise to a plain dict (for SSE events / logging)."""
        return {
            "query": self.query,
            "is_fast_path": self.is_fast_path,
            "steps": [
                {
                    "step_id": s.step_id,
                    "tool_name": s.tool_name,
                    "params": s.params,
                    "depends_on": s.depends_on,
                    "affordance": s.affordance.value,
                    "rationale": s.rationale,
                    "is_parallel": s.is_parallel,
                }
                for s in self.steps
            ],
            "conflict_notes": self.conflict_notes,
            "planner_version": self.planner_version,
        }


# ---------------------------------------------------------------------------
# Fast-path detection
# ---------------------------------------------------------------------------

# Tools that are meta/utility and should NEVER be chosen by the fast-path
# heuristic regardless of their retrieval rank.  The LLM is required to
# decide when these are appropriate.
_FAST_PATH_BLOCKED_TOOLS: frozenset = frozenset({
    # ---- Azure MCP utility meta-tools (require 'command'/'learn' arg) ----
    "documentation", "learn", "help", "feedback", "version",
    # ---- CLI scaffolding ----
    "azd",   # Azure Developer CLI
    "az",    # raw Azure CLI passthrough
    # ---- Azure MCP SERVICE CATEGORY wrappers ----
    # These are group/namespace tools that return "command required" when called
    # without a sub-command argument.  They are never the correct direct tool
    # for a read query — real list/get tools have underscores (e.g. subscription_list).
    "role", "deploy", "get_azure_bestpractices",
    "compute",           # group: VMs, VMSS etc — use virtual_machine_list etc.
    "virtualdesktop",   # group: AVD
    "appconfig",        # group: App Configuration
    "aks",              # group: Kubernetes
    "applens",          # group: App Lens diagnostics
    "appservice",       # group: App Service
    "datadog",          # group: Datadog integration
    "managedlustre",    # group: Managed Lustre
    "azuremigrate",     # group: Azure Migrate
    "azureterraformbestpractices",  # doc lookup
    "network",          # group: generic network namespace (not the network MCP source)
    "storage",          # group: storage namespace
    "keyvault",         # group: Key Vault namespace
    "sql",              # group: SQL namespace
    "cosmosdb",         # group: Cosmos DB namespace
    "monitor",          # group: Monitor namespace (different from monitor MCP source)
    "security",         # group: Security Center namespace
    "policy",           # group: Azure Policy namespace
    "billing",          # group: Billing namespace
    "advisor",          # group: Azure Advisor namespace
    # Network action tools — require specific src/dst params, never valid for list queries
    "test_network_connectivity",
    "check_dns_resolution",
})

_FAST_PATH_PATTERNS = re.compile(
    r"""
    ^\s*(?:
        (?:list|show|get|display|fetch|find|describe|enumerate)\s
        |what\s+(?:are|is)\s+(?:my|the)\s
        |(?:how\s+many)\s
        |summarize\s
    )
    """,
    re.IGNORECASE | re.VERBOSE,
)

_MULTI_STEP_KEYWORDS = re.compile(
    r"\b(?:then|after(?:\s+that)?|also|and\s+then|followed\s+by|next|finally|"
    r"restart|remediat|fix|updat|deploy|delet|creat|scale|assign|enable|disable)\b",
    re.IGNORECASE,
)


def is_simple_read_query(query: str) -> bool:
    """Return True when the query is a single-step, read-only lookup.

    Fast-path heuristic — avoids an LLM call for ≥60% of production queries.
    Conservative: returns False whenever a multi-step keyword is detected, even
    if the base pattern matches (e.g. "list my VMs then restart the failed one").

    Args:
        query: Raw user query string.

    Returns:
        True only when it is safe to skip the planner LLM call.
    """
    if _MULTI_STEP_KEYWORDS.search(query):
        return False
    return bool(_FAST_PATH_PATTERNS.match(query.strip()))


# Stop-words not useful for tool matching
_STOP_WORDS = frozenset({
    "a", "an", "the", "my", "our", "your", "its", "their",
    "i", "me", "we", "you", "he", "she", "it", "they",
    "is", "are", "was", "were", "be", "been", "being",
    "have", "has", "had", "do", "does", "did", "will",
    "would", "could", "should", "can", "may", "might",
    "in", "on", "at", "by", "for", "of", "to", "from",
    "with", "about", "into", "through", "during",
    "all", "any", "both", "each", "few", "more", "most",
    "other", "some", "such", "no", "not", "only", "own",
    "same", "so", "than", "too", "very", "and", "or", "but",
    "what", "which", "who", "that", "this", "these", "those",
    "show", "list", "get", "display", "fetch", "find",
    "describe", "enumerate", "how", "many",
})


def _pick_fast_path_tool(query: str, tool_names: List[str]) -> Optional[str]:
    """Return the best tool name for a fast-path read query, or *None* to fall
    through to the LLM planner.

    Selection rules (in priority order):
    1. Blocked tool names (``documentation``, ``learn``, etc.) are never chosen.
    2. Score each candidate by keyword overlap: split the query and tool name
       into tokens and count how many query tokens appear in the tool name.
    3. Return the highest-scoring tool **only** if its score > 0.
    4. Return *None* when no keyword overlap exists — this forces the LLM path
       so it can make a smarter choice.

    Args:
        query:      Raw user query string.
        tool_names: Ordered list of candidate tool names from retrieval.

    Returns:
        Best tool name, or None.
    """
    # Filter out blocked tools
    candidates = [t for t in tool_names if t.lower() not in _FAST_PATH_BLOCKED_TOOLS]
    if not candidates:
        return None

    # Tokenise query: lowercase words minus stop-words
    query_tokens = {
        w for w in re.findall(r"[a-z]+", query.lower())
        if w not in _STOP_WORDS and len(w) > 2
    }

    # Expand common Azure abbreviations so 'virtual'+'network' → also matches 'vnet',
    # 'virtual'+'machine' → 'vm', 'network'+'security' → 'nsg', etc.
    if "virtual" in query_tokens and ("network" in query_tokens or "networks" in query_tokens):
        query_tokens.add("vnet")
    if "virtual" in query_tokens and ("machine" in query_tokens or "machines" in query_tokens):
        query_tokens.add("vm")
    if "network" in query_tokens and "security" in query_tokens:
        query_tokens.add("nsg")
    if "resource" in query_tokens and "group" in query_tokens:
        query_tokens.add("rg")

    if not query_tokens:
        # No meaningful tokens — use first non-blocked candidate (keeps old
        # behaviour for very short / single-word queries)
        return candidates[0]

    best_name: Optional[str] = None
    best_score: int = 0

    for name in candidates:
        # Tokenise the tool name by splitting on _ and - so that 'virtual'
        # matches 'virtual_network_list' but NOT 'virtualdesktop'.
        tool_tokens = set(re.findall(r"[a-z0-9]+", name.lower()))
        score = 0
        for qt in query_tokens:
            variants = {qt}
            if qt.endswith("s") and len(qt) > 3:
                variants.add(qt[:-1])   # subscriptions → subscription
            else:
                variants.add(qt + "s")  # subscription → subscriptions
            if any(v in tool_tokens for v in variants):
                score += 1
        if score > best_score:
            best_score = score
            best_name = name

    # Only fast-path if at least one keyword matched; otherwise defer to LLM
    return best_name if best_score > 0 else None


# ---------------------------------------------------------------------------
# JSON schema the planner asks the LLM to produce
# ---------------------------------------------------------------------------

_PLAN_JSON_SCHEMA = {
    "type": "object",
    "required": ["steps"],
    "properties": {
        "steps": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["step_id", "tool_name", "params", "depends_on", "rationale"],
                "properties": {
                    "step_id":    {"type": "string"},
                    "tool_name":  {"type": "string"},
                    "params":     {"type": "object"},
                    "depends_on": {"type": "array", "items": {"type": "string"}},
                    "rationale":  {"type": "string"},
                    "is_parallel": {"type": "boolean"},
                },
            },
        }
    },
}


def _build_planner_system_prompt() -> str:
    return """You are the Azure operations Planner.

Given a user query, a set of available tools, and an environment grounding summary,
output a JSON execution plan with the following schema:

{
  "steps": [
    {
      "step_id": "step_1",
      "tool_name": "<exact tool name from the available list>",
      "params": { "<param>": "<value or placeholder>" },
      "depends_on": [],
      "rationale": "<one sentence>",
      "is_parallel": false
    }
  ]
}

Rules:
1. Use ONLY tool names from the AVAILABLE TOOLS list.
2. Pre-fill params from the grounding summary where possible.
3. Use placeholder strings like "<resource_group>" when unknown.
4. Set is_parallel=true for steps with no depends_on that can run concurrently.
5. Do NOT add a "response_compose" step — that is handled separately.
6. Output ONLY valid JSON — no markdown fences, no prose.
7. Minimum 1 step, maximum 5 steps.
8. If the query needs only one tool call, output a single step.
9. If a step modifies Azure state, mark its params with a "_destructive": true field.
"""


def _build_planner_user_prompt(
    query: str,
    tool_names: List[str],
    grounding_summary: Optional[GroundingSummary],
    conflict_notes: str,
) -> str:
    grounding_dict: Dict[str, Any] = {}
    if grounding_summary:
        grounding_dict = {
            "tenant_id": grounding_summary.tenant_id,
            "subscriptions": grounding_summary.subscriptions,
            "resource_groups": grounding_summary.resource_groups[:10],
            "resource_type_counts": grounding_summary.resource_type_counts,
        }

    parts = [
        f"USER QUERY: {query}",
        "",
        f"AVAILABLE TOOLS ({len(tool_names)}):",
        *[f"  - {name}" for name in tool_names],
        "",
        f"GROUNDING SUMMARY:\n{json.dumps(grounding_dict, indent=2)}",
    ]
    if conflict_notes:
        parts += ["", f"TOOL DISAMBIGUATION NOTES:\n{conflict_notes}"]

    parts += ["", "Output the JSON execution plan now:"]
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Planner class
# ---------------------------------------------------------------------------


class Planner:
    """Pipeline Planner — produces an ExecutionPlan from a query + tool set.

    Usage::

        planner = Planner()
        plan = await planner.plan(
            query="check health of prod-api",
            retrieval_result=result,
            grounding_summary=summary,
        )
    """

    def __init__(
        self,
        manifest_index: Optional[Any] = None,
    ) -> None:
        """Initialise the Planner.

        Args:
            manifest_index: Optional ``ToolManifestIndex`` for affordance lookup.
                If None, affordance defaults to READ for all steps.
        """
        self._manifest_index = manifest_index

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    async def plan(
        self,
        query: str,
        retrieval_result: ToolRetrievalResult,
        grounding_summary: Optional[GroundingSummary] = None,
    ) -> ExecutionPlan:
        """Produce an ``ExecutionPlan`` for *query*.

        Fast-path:
            If ``is_simple_read_query(query)`` and ``retrieval_result`` has
            exactly one candidate tool, returns a synthetic 1-step plan without
            an LLM call.

        LLM path:
            Calls Azure OpenAI with a structured JSON prompt (temperature=0.1)
            and parses the response into ``PlanStep`` objects.

        Fallback:
            If the LLM is unavailable or returns invalid JSON, emits a single
            "legacy_react" step so the orchestrator can fall back to the ReAct
            loop.

        Args:
            query: Raw user query string.
            retrieval_result: Output of ``ToolRetriever.retrieve()``.
            grounding_summary: Optional ``GroundingSummary`` from
                ``ResourceInventoryService.get_grounding_summary()``.

        Returns:
            ``ExecutionPlan`` — always non-empty (at least one step).
        """
        tools = retrieval_result.tools
        conflict_notes = retrieval_result.conflict_notes
        tool_names = [
            t.get("function", {}).get("name", "") for t in tools if t.get("function")
        ]
        # Strip meta / documentation-only tools so the LLM never picks them
        tool_names = [t for t in tool_names if t.lower() not in _FAST_PATH_BLOCKED_TOOLS]

        # ── Fast-path: single read query, skip LLM call ────────────────
        logger.debug("⚡ Planner: 15 candidate tool_names=%s", tool_names)
        if tool_names and is_simple_read_query(query):
            best_tool = _pick_fast_path_tool(query, tool_names)
            if best_tool:
                step = PlanStep(
                    step_id="step_1",
                    tool_name=best_tool,
                    params={},
                    affordance=self._get_affordance(best_tool),
                    rationale="Fast-path: single-step read query.",
                    is_parallel=False,
                )
                logger.debug("⚡ Planner fast-path: tool=%s", best_tool)
                return ExecutionPlan(
                    query=query,
                    steps=[step],
                    is_fast_path=True,
                    conflict_notes=conflict_notes,
                )
            logger.debug("⚡ Planner fast-path: no keyword match for %r — falling through to LLM", query)

        # ── LLM path ───────────────────────────────────────────────────
        if not tool_names:
            logger.warning("Planner: no tools in retrieval_result; emitting legacy fallback step")
            return self._legacy_fallback_plan(query, conflict_notes)

        system_prompt = _build_planner_system_prompt()
        user_prompt = _build_planner_user_prompt(
            query, tool_names, grounding_summary, conflict_notes
        )

        ok, raw_text = await self._call_llm(system_prompt, user_prompt, temperature=0.1)
        if not ok:
            logger.warning("Planner: LLM call failed; using legacy fallback plan")
            return self._legacy_fallback_plan(query, conflict_notes)

        steps = self._parse_steps(raw_text, tool_names)
        if not steps:
            logger.warning("Planner: could not parse LLM response; using legacy fallback plan")
            return self._legacy_fallback_plan(query, conflict_notes)

        logger.info(
            "📋 Planner produced %d step(s) for query (fast_path=False): %s",
            len(steps),
            [s.tool_name for s in steps],
        )
        return ExecutionPlan(
            query=query,
            steps=steps,
            is_fast_path=False,
            conflict_notes=conflict_notes,
        )

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _get_affordance(self, tool_name: str) -> ToolAffordance:
        if self._manifest_index is None:
            return ToolAffordance.READ
        return self._manifest_index.get_affordance(tool_name)

    def _legacy_fallback_plan(self, query: str, conflict_notes: str) -> ExecutionPlan:
        """Return a 1-step plan that asks the legacy ReAct loop to handle the query."""
        return ExecutionPlan(
            query=query,
            steps=[
                PlanStep(
                    step_id="step_1",
                    tool_name="legacy_react",
                    params={"query": query},
                    affordance=ToolAffordance.READ,
                    rationale="Planner fallback: no tools available or LLM error.",
                )
            ],
            is_fast_path=False,
            conflict_notes=conflict_notes,
        )

    def _parse_steps(
        self,
        raw_text: str,
        valid_tool_names: List[str],
    ) -> List[PlanStep]:
        """Parse LLM JSON response into a list of PlanStep objects.

        Returns empty list on parse failure.
        """
        # Strip optional markdown fences
        text = raw_text.strip()
        if text.startswith("```"):
            text = re.sub(r"^```(?:json)?\n?", "", text, flags=re.IGNORECASE)
            text = re.sub(r"\n?```$", "", text)

        try:
            data = json.loads(text)
        except json.JSONDecodeError as exc:
            logger.debug("Planner JSON parse error: %s | raw=%s", exc, raw_text[:200])
            return []

        raw_steps = data.get("steps") if isinstance(data, dict) else None
        if not isinstance(raw_steps, list) or not raw_steps:
            return []

        valid_name_set = set(valid_tool_names)
        steps: List[PlanStep] = []
        for i, raw in enumerate(raw_steps[:5]):  # cap at 5 steps
            if not isinstance(raw, dict):
                continue
            tool_name = raw.get("tool_name", "")
            if tool_name not in valid_name_set:
                # Try first valid tool as fallback for this step
                logger.debug(
                    "Planner: tool_name %r not in valid set; skipping step %d", tool_name, i + 1
                )
                continue
            step_id = raw.get("step_id") or f"step_{i + 1}"
            params = raw.get("params") or {}
            if not isinstance(params, dict):
                params = {}
            depends_on = raw.get("depends_on") or []
            if not isinstance(depends_on, list):
                depends_on = []
            rationale = raw.get("rationale", "")
            is_parallel = bool(raw.get("is_parallel", False))
            affordance = self._get_affordance(tool_name)
            # Override with manifest if _destructive flag present in params
            if params.pop("_destructive", False):
                affordance = ToolAffordance.DESTRUCTIVE
            steps.append(
                PlanStep(
                    step_id=str(step_id),
                    tool_name=tool_name,
                    params=params,
                    depends_on=[str(d) for d in depends_on],
                    affordance=affordance,
                    rationale=str(rationale),
                    is_parallel=is_parallel,
                )
            )

        return steps

    async def _call_llm(
        self,
        system_prompt: str,
        user_prompt: str,
        temperature: float = 0.1,
        max_tokens: int = 800,
    ) -> tuple[bool, str]:
        """Make a single LLM call (no tools).

        Returns (success, text_content).
        """
        try:
            from openai import AsyncAzureOpenAI

            endpoint = os.getenv("AZURE_OPENAI_ENDPOINT", "")
            if not endpoint:
                return False, "AZURE_OPENAI_ENDPOINT not set"

            api_key = os.getenv("AZURE_OPENAI_API_KEY")
            api_version = os.getenv("AZURE_OPENAI_API_VERSION", "2024-08-01-preview")
            deployment = (
                os.getenv("AZURE_OPENAI_CHAT_DEPLOYMENT_NAME")
                or os.getenv("AZURE_OPENAI_DEPLOYMENT", "gpt-4o-mini")
            )

            async_credential = None
            if api_key:
                client = AsyncAzureOpenAI(
                    api_key=api_key,
                    azure_endpoint=endpoint,
                    api_version=api_version,
                )
            else:
                from azure.identity.aio import (  # type: ignore[import-not-found]
                    DefaultAzureCredential as AsyncDefaultAzureCredential,
                )
                async_credential = AsyncDefaultAzureCredential(
                    exclude_interactive_browser_credential=True,
                    exclude_shared_token_cache_credential=True,
                    exclude_visual_studio_code_credential=True,
                    exclude_powershell_credential=True,
                )
                token = await async_credential.get_token(
                    "https://cognitiveservices.azure.com/.default"
                )
                client = AsyncAzureOpenAI(
                    api_key=token.token,
                    azure_endpoint=endpoint,
                    api_version=api_version,
                )

            try:
                raw = await client.chat.completions.create(
                    model=deployment,
                    messages=[
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_prompt},
                    ],
                    temperature=temperature,
                    max_tokens=max_tokens,
                    response_format={"type": "json_object"},
                )
            finally:
                await client.close()
                if async_credential:
                    await async_credential.close()

            content = raw.choices[0].message.content or ""
            return True, content

        except Exception as exc:  # pylint: disable=broad-except
            logger.error("Planner LLM call failed: %s", exc)
            return False, str(exc)
